#!/bin/bash
set -ex

brew install bash
EXE_LOCATION="$(brew --prefix)/Cellar/bash/$(brew info --json=v1 bash | jq -r '.[0].linked_keg')/bin/bash"
echo $EXE_LOCATION | sudo tee -a /etc/shells
chsh -s $EXE_LOCATION
