#!/bin/bash
set -ex

brew install neovim
mkdir -p ~/.config/nvim/ || true
cat > ~/.config/nvim/init.vim <<EOF
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF

# Set up Python environments for Neovim
mkdir ~/.config/nvim/python2-neovim/ || true
cd ~/.config/nvim/python2-neovim/
pipenv --two
pipenv install neovim
echo "let g:python_host_prog = '$(pipenv run which python)'" >> ~/.vimrc
cd -

mkdir ~/.config/nvim/python3-neovim/ || true
cd ~/.config/nvim/python3-neovim/
pipenv --three
pipenv install neovim
echo "let g:python3_host_prog = '$(pipenv run which python)'" >> ~/.vimrc
cd -

nvim +UpdateRemotePlugins
